/**
 * Docusaurus sidebar configuration.
 * This sidebar is named 'tutorialSidebar' to match the navbar config.
 * It will automatically generate sidebar items from the docs folder.
 */

export default {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    },
  ],
};